Repository AllianceBioversityCIAT/onecgiar_pr, pull requests merged in 2024-08, with the labels that each got.

#293 * Feat added Created by column for General excel report and applied new styles and format
  onecgiar-pr-client/src/app/custom-fields/pr-select/pr-select.component.html
  onecgiar-pr-client/src/app/custom-fields/pr-select/pr-select.component.ts
  onecgiar-pr-client/src/app/pages/admin-section/admin-section.component.ts
  onecgiar-pr-client/src/app/pages/admin-section/pages/knowledge-products/knowledge-products-routing.module.ts
  onecgiar-pr-client/src/app/pages/admin-section/pages/knowledge-products/knowledge-products.component.html
  onecgiar-pr-client/src/app/pages/admin-section/pages/knowledge-products/knowledge-products.component.scss
  onecgiar-pr-client/src/app/pages/admin-section/pages/knowledge-products/knowledge-products.component.spec.ts
  onecgiar-pr-client/src/app/pages/admin-section/pages/knowledge-products/knowledge-products.component.ts
  onecgiar-pr-client/src/app/pages/admin-section/pages/knowledge-products/knowledge-products.module.ts
  onecgiar-pr-client/src/app/pages/init-admin-section/pages/init-general-results-report/init-general-results-report.component.spec.ts
  onecgiar-pr-client/src/app/pages/init-admin-section/pages/init-general-results-report/init-general-results-report.component.ts
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-partners/components/knowledge-product-selector/knowledge-product-selector.component.html
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-partners/components/knowledge-product-selector/knowledge-product-selector.component.ts
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-partners/models/partnersBody.ts
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-partners/rd-partners.component.ts
  onecgiar-pr-client/src/app/shared/routing/routing-data.ts
  onecgiar-pr-client/src/app/shared/services/api/results-api.service.ts
  onecgiar-pr-client/src/app/shared/services/data-control.service.spec.ts
  onecgiar-pr-client/src/app/shared/services/data-control.service.ts
  onecgiar-pr-client/src/app/shared/services/export-tables.service.spec.ts
  onecgiar-pr-client/src/app/shared/services/export-tables.service.ts
  onecgiar-pr-client/src/app/shared/services/global-variables.service.ts
  onecgiar-pr-server/src/api/results/entities/result.entity.ts
  onecgiar-pr-server/src/api/results/result.repository.ts
  onecgiar-pr-server/src/api/results/result_budget/entities/result_institutions_budget.entity.ts
  onecgiar-pr-server/src/api/results/results-knowledge-products/entities/results-knowledge-product-institution.entity.ts
  onecgiar-pr-server/src/api/results/results-knowledge-products/results-knowledge-products.mapper.ts
  onecgiar-pr-server/src/api/results/results-knowledge-products/results-knowledge-products.service.ts
  onecgiar-pr-server/src/api/results/results_by_institutions/entities/results_by_institution.entity.ts
  onecgiar-pr-server/src/api/results/results_by_institutions/results_by_institutions.service.ts
  onecgiar-pr-server/src/shared/utils/change-tracker.ts
Labels: enhancement

#294 Creating M-QAP report (back-end) and updating Global Variables
  onecgiar-pr-server/src/api/global-parameter/dto/update-global-parameter.dto.ts
  onecgiar-pr-server/src/api/global-parameter/global-parameter.controller.ts
  onecgiar-pr-server/src/api/global-parameter/global-parameter.module.ts
  onecgiar-pr-server/src/api/global-parameter/global-parameter.service.ts
  onecgiar-pr-server/src/api/results/results-knowledge-products/dto/filter.dto.ts
  onecgiar-pr-server/src/api/results/results-knowledge-products/repositories/results-knowledge-products.repository.ts
  onecgiar-pr-server/src/api/results/results-knowledge-products/results-knowledge-products.controller.ts
  onecgiar-pr-server/src/api/results/results-knowledge-products/results-knowledge-products.service.ts
Labels: bug, enhancement

#297 * Fix Applied correctly the url structure of the "See ToC" button.
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-theory-of-change/components/shared/toc-initiative-out/toc-initiative-out.component.spec.ts
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-theory-of-change/components/shared/toc-initiative-out/toc-initiative-out.component.ts
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-theory-of-change/rd-theory-of-changes-services.service.ts
  onecgiar-pr-client/src/app/shared/services/api/results-api.service.spec.ts
  onecgiar-pr-client/src/app/shared/services/api/results-api.service.ts
  onecgiar-pr-server/src/api/results/result-questions/repository/result-answers.repository.ts
  onecgiar-pr-server/src/api/results/results-knowledge-products/results-knowledge-products.service.ts
  onecgiar-pr-server/src/api/results/results-toc-results/dto/update-results-toc-result.dto.ts
  onecgiar-pr-server/src/api/results/results-toc-results/results-toc-results.controller.ts
  onecgiar-pr-server/src/api/results/results-toc-results/results-toc-results.service.ts
Labels: bug

#298 * Feat Added connection to Reports and File Management Microservices
  onecgiar-pr-client/src/app/custom-fields/pr-button/pr-button.component.scss
  onecgiar-pr-client/src/app/custom-fields/pr-radio-button/pr-radio-button.component.scss
  onecgiar-pr-client/src/app/pages/pdf-reports/pdf-reports.component.html
  onecgiar-pr-client/src/app/pages/pdf-reports/pdf-reports.component.ts
  onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-list/results-list.component.html
  onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-list/results-list.component.scss
  onecgiar-pr-server/package-lock.json
  onecgiar-pr-server/package.json
  onecgiar-pr-server/src/api/platform-report/platform-report.controller.ts
  onecgiar-pr-server/src/api/platform-report/platform-report.module.ts
  onecgiar-pr-server/src/api/platform-report/platform-report.service.ts
Labels: enhancement
