Repository AllianceBioversityCIAT/onecgiar_pr, pull requests merged in 2024-01, with the labels that each got.

#215 * Fix validation logic for Innovation Development Completeness Status
  onecgiar-pr-server/src/api/results/results-validation-module/results-validation-module.repository.ts
Labels: bug

#217 * Fix logic to map multiple WPs to multiple
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-theory-of-change/rd-theory-of-change.component.ts
  onecgiar-pr-server/src/api/results/results-toc-results/results-toc-results.repository.ts
  onecgiar-pr-server/src/api/results/results-toc-results/results-toc-results.service.ts
Labels: bug

#218 * Feat: New features and performance improvements
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-general-information/rd-general-information.component.ts
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-geographic-location/rd-geographic-location.component.ts
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-partners/rd-partners.component.ts
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/innovation-dev-info/components/anticipated-innovation-user/anticipated-innovation-user.component.html
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/innovation-dev-info/components/anticipated-innovation-user/anticipated-innovation-user.component.ts
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/knowledge-product-info/knowledge-product-info.component.ts
  onecgiar-pr-server/src/api/results/results-toc-results/results-toc-results.repository.ts
  onecgiar-pr-server/src/result-dashboard-bi/bi-reports/repository/bi-report.repository.ts
Labels: bug, enhancement

#220 * Refactor added missing alert and improve validations for Contributors Init ToC mapping
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/innovation-dev-info/components/estimates/estimates.component.html
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/innovation-dev-info/components/estimates/estimates.component.ts
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/knowledge-product-info/knowledge-product-info.component.html
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/knowledge-product-info/knowledge-product-info.module.ts
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-theory-of-change/components/shared/toc-initiative-out/toc-initiative-out.component.html
  onecgiar-pr-server/src/api/results/results-toc-results/results-toc-results.repository.ts
  onecgiar-pr-server/src/api/results/results-toc-results/results-toc-results.service.ts
Labels: bug

#221 * Refactor Improve validation to match the Contributing Init according the mapped multiple WPs
  onecgiar-pr-server/src/api/results/results-validation-module/results-validation-module.repository.ts
Labels: enhancement

#223 Error resolution in base phase and notifications; adjustment of contributing indicators listing.
  onecgiar-pr-client/src/app/pages/ipsr/pages/innovation-package-list-content/pages/innovation-packages-notification/component/notification-item-innovation/notification-item-innovation.component.ts
  onecgiar-pr-client/src/app/pages/results/pages/results-outlet/pages/results-notifications/components/notification-item/notification-item.component.ts
  onecgiar-pr-server/src/api/results/linked-results/linked-results.service.ts
  onecgiar-pr-server/src/api/results/result-by-institutions-by-deliveries-type/entities/result-by-institutions-by-deliveries-type.entity.ts
  onecgiar-pr-server/src/api/results/result-by-institutions-by-deliveries-type/result-by-institutions-by-deliveries-type.repository.ts
  onecgiar-pr-server/src/api/results/result-countries/result-countries.service.ts
  onecgiar-pr-server/src/api/results/result-regions/result-regions.service.ts
  onecgiar-pr-server/src/api/results/results-toc-results/results-toc-results.repository.ts
  onecgiar-pr-server/src/api/results/results_by_institutions/results_by_institutions.service.ts
  onecgiar-pr-server/src/api/results/summary/summary.service.ts
  onecgiar-pr-server/src/migrations/1705417087587-deleteVersionIdIntoSummarydeliveriesType.ts
Labels: bug, enhancement

#224 * Feat performance improvements and bug fixes
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-partners/rd-partners.component.html
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-result-types-pages/cap-dev-info/cap-dev-info.component.html
  onecgiar-pr-client/src/app/shared/components/navigation-bar/navigation-bar.component.scss
  onecgiar-pr-server/src/api/platform-report/platform-report.service.ts
  onecgiar-pr-server/src/api/results/results-toc-results/results-toc-results.repository.ts
  onecgiar-pr-server/src/api/results/results-toc-results/results-toc-results.service.ts
Labels: bug, enhancement

#227 * Feat performance improvements and bug fixes
  onecgiar-pr-client/src/app/pages/ipsr/pages/innovation-package-detail/pages/ipsr-innovation-use-pathway/pages/step-n1/components/step-n1-experts/step-n1-experts.component.html
  onecgiar-pr-server/src/api/ipsr/results-innovation-packages-validation-module/results-innovation-packages-validation-module.repository.ts
  onecgiar-pr-server/src/api/results/results-toc-results/results-toc-results.service.ts
Labels: bug, enhancement

#228 * Refactor ToC error when adding an Contributing Initiative
  onecgiar-pr-server/src/api/results/results_by_inititiatives/resultByInitiatives.repository.ts
Labels: bug, enhancement

#236 * Feat new features, performance improvements and bug fixes
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-evidences/rd-evidences.component.ts
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-theory-of-change/model/theoryOfChangeBody.ts
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-theory-of-change/rd-theory-of-change.component.html
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/pages/rd-theory-of-change/rd-theory-of-change.component.ts
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/panel-menu/panel-menu.component.html
  onecgiar-pr-client/src/app/pages/results/pages/result-detail/panel-menu/panel-menu.component.ts
  onecgiar-pr-client/src/app/shared/services/api/results-api.service.spec.ts
  onecgiar-pr-client/src/app/shared/services/api/results-api.service.ts
  onecgiar-pr-server/src/api/ipsr/results-package-toc-result/dto/create-results-package-toc-result.dto.ts
  onecgiar-pr-server/src/api/results/evidences/dto/create-upload-session.dto.ts
  onecgiar-pr-server/src/api/results/evidences/evidences.repository.ts
  onecgiar-pr-server/src/api/results/evidences/evidences.service.ts
  onecgiar-pr-server/src/api/results/results-toc-results/dto/create-results-toc-result.dto.ts
  onecgiar-pr-server/src/api/results/results-toc-results/results-toc-results.service.ts
  onecgiar-pr-server/src/api/results/results_by_inititiatives/resultByInitiatives.repository.ts
  onecgiar-pr-server/src/api/results/share-result-request/dto/create-share-result-request.dto.ts
  onecgiar-pr-server/src/result-dashboard-bi/bi-reports/repository/bi-report.repository.ts
  onecgiar-pr-server/src/shared/services/share-point/share-point.service.ts
Labels: bug, enhancement
